name: Star Wars Episode I Racer (Japan retail)
sha1: 9577ccd2d069d0e7e306cf21ddb0e4765a308072

options:
  basename: podcruise.jp
  target_path: "roms/originals/baserom.jp.z64"
  elf_path: build/jp/podcruise.jp.elf
  base_path: ..
  platform: n64
  compiler: IDO

  asm_path: analysis/generated/jp/asm
  asset_path: analysis/generated/jp/assets
  src_path: src
  build_path: build/jp
  cache_path: .cache/splat/jp
  generated_asm_macros_directory: analysis/generated/jp/include
  ld_script_path: analysis/generated/jp/podcruise.jp.ld
  ld_dependencies: true

  find_file_boundaries: true
  disassemble_all: true
  header_encoding: ASCII
  o_as_suffix: true
  use_legacy_include_asm: false
  mips_abi_float_regs: o32

  symbol_addrs_path:
    - config/jp/symbol_addrs.auto.txt
  reloc_addrs_path:
    - config/jp/reloc_addrs.txt
  undefined_funcs_auto_path: analysis/generated/jp/undefined_funcs_auto.txt
  undefined_syms_auto_path: analysis/generated/jp/undefined_syms_auto.txt

segments:
  - name: header
    type: header
    start: 0x0

  - name: ipl3
    type: bin
    start: 0x40

  - name: main
    type: code
    start: 0x1000
    vram: 0x80000400
    subsegments:
      - [0x1000, asm, main]

  # USA bootstrap endpoint translated by the final stable JP delta (+0xCF0).
  - name: remainder
    type: bin
    start: 0x99CF0
    follows_vram: main

  - [0x2000000]
