#!/usr/bin/env python3
"""Regenerate the weak link-only doubles the host test needs.

`tests/host_link_stubs.c` stands in for game symbols that the recovered source
references but that no recovered source defines yet. That set changes every
time a function is recovered, so the file is generated rather than maintained:
a stale entry is harmless but a missing one breaks the host-test link, and a
symbol that has since been recovered for real should stop being stubbed.

Symbols that `tests/test_global_state.c` defines as observable doubles are
treated as defined here, matching the Makefile rule that drops their recovered
sources from the host-test link.
"""
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAME_SYMBOL = re.compile(r"^(?:func|D|B)_[0-9A-F]{6,8}(?:_[0-9]+)?$")
HEADER = """/* Weak link-only doubles for game dependencies outside this source tranche. */
/* Generated by tools/gen_host_stubs.py; do not edit by hand. */
#define WEAK __attribute__((weak))

/* Sized and aligned generously: recovered sources index these game objects
   as tables, so a scalar double would under-allocate the host stand-in. */
#define STUB_GLOBAL(name) WEAK double name[256]
#define STUB_VOID(name) WEAK void name(void) {}
"""


def symbols() -> tuple[set[str], set[str]]:
    defined: set[str] = set()
    undefined: set[str] = set()
    with tempfile.TemporaryDirectory() as tmp:
        for source in sorted((ROOT / "src").rglob("*.c")):
            obj = pathlib.Path(tmp) / (source.stem + ".o")
            built = subprocess.run(
                ["gcc", "-std=c11", "-I", "include", "-c", str(source), "-o", str(obj)],
                cwd=ROOT, capture_output=True, text=True)
            if built.returncode != 0:
                # A worker may be mid-write; skip rather than lose the whole run.
                print(f"skipped (does not compile): {source}", file=sys.stderr)
                continue
            listing = subprocess.run(["nm", str(obj)], capture_output=True,
                                     text=True).stdout
            for line in listing.splitlines():
                parts = line.split()
                if len(parts) == 2 and parts[0] == "U":
                    undefined.add(parts[1])
                elif len(parts) == 3 and parts[1] in "TtDdBbRr":
                    defined.add(parts[2])
    return defined, undefined


def doubled() -> set[str]:
    text = (ROOT / "tests/test_global_state.c").read_text(encoding="utf-8")
    return set(re.findall(r"^[A-Za-z_][A-Za-z0-9_ *]*?(func_[0-9A-F]{8})\(",
                          text, re.MULTILINE))


def main() -> int:
    defined, undefined = symbols()
    needed = sorted(s for s in undefined - defined - doubled()
                    if GAME_SYMBOL.match(s))
    body = "\n".join(f"STUB_VOID({s});" if s.startswith("func_")
                     else f"STUB_GLOBAL({s});" for s in needed)
    target = ROOT / "tests/host_link_stubs.c"
    text = HEADER + "\n" + body + "\n"
    if target.read_text(encoding="utf-8") != text:
        target.write_text(text, encoding="utf-8")
        print(f"regenerated {target.name}: {len(needed)} stubs")
    else:
        print(f"{target.name} already current: {len(needed)} stubs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
