#!/usr/bin/env python3
"""Turn unique cross-version mappings into autogenerated regional symbols."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def format_symbol(address: int) -> str:
    return f"func_{address:08X} = 0x{address:08X}; // type:func\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mappings", type=Path, required=True)
    parser.add_argument("--target", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    mapped: dict[int, tuple[str, str]] = {}
    with args.mappings.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if row["target"] != args.target or row["status"] != "unique_match":
                continue
            address = int(row["target_vram"], 0)
            mapped[address] = (row["source_name"], row["delta_bytes"])

    # Every supplied retail build has the same entry VRAM.
    mapped.setdefault(0x80000400, ("entry", "0"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("// Auto-derived unique structural mappings; verify every boundary.\n")
        for address, (source_name, delta) in sorted(mapped.items()):
            # Splat parses comma-separated text following type: as part of the
            # type value. Mapping provenance lives in the CSV; keep this input
            # deliberately minimal and machine-readable.
            handle.write(format_symbol(address))
    print(f"{args.target}: wrote {len(mapped):,} autogenerated function symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
