#!/usr/bin/env python3
"""Render deterministic analysis JSON into a concise Markdown report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def render_report(
    inventory: dict,
    functions: dict,
    compiler: dict,
    mappings: dict,
    rebuilds: list[dict],
    bootstrap: dict | None,
    manifest: dict | None = None,
) -> str:
    lines = [
        "# Bootstrap analysis report",
        "",
        "> Generated by `make report`; contains metadata only.",
        "",
        "## ROM identity",
        "",
        "| ID | Game code | Rev | CRC32 | Build stamp | Role |",
        "|---|---|---:|---|---|---|",
    ]
    for rom in inventory["roms"]:
        builds = ", ".join(f"`{value}`" for value in rom["build_stamps"]) or "-"
        lines.append(
            f"| {rom['id']} | `{rom['header']['game_code']}` | "
            f"{rom['header']['revision']} | `{rom['crc32'].upper()}` | "
            f"{builds} | {rom['role']} |"
        )

    lines.extend(
        [
            "",
            f"The six filenames represent **{inventory['unique_rom_count']} unique ROM images**.",
            "",
            "## USA function-boundary evidence",
            "",
            f"The conservative first pass found **{functions['candidate_count']:,} candidates** "
            f"in `{functions['code_start']}`–`{functions['code_end']}`.",
            "",
            "| Confidence | Candidates |",
            "|---|---:|",
        ]
    )

    for level in ("high", "medium", "low"):
        if level in functions["by_confidence"]:
            lines.append(f"| {level} | {functions['by_confidence'][level]:,} |")

    if rebuilds:
        lines.extend(
            [
                "",
                "## ROM rebuild verification",
                "",
                "| Version | Byte-identical | SHA-1 | C functions substituted |",
                "|---|---|---|---:|",
            ]
        )
        for rebuild in rebuilds:
            lines.append(
                f"| {rebuild['version']} | {str(rebuild['byte_identical']).lower()} | "
                f"`{rebuild['rebuilt_sha1']}` | "
                f"{rebuild.get('c_functions_substituted', 0)} |"
            )
        lines.extend(
            [
                "",
                "Each nonzero count is verified matching C substituted into that version's "
                "otherwise local assembly/data round trip.",
            ]
        )

    if manifest is not None:
        lines.extend(
            [
                "",
                "## Recovered source ledger",
                "",
                "Counted by `tools/make_source_manifest.py` from the matching "
                "configuration and the per-version comparison reports, so these "
                "numbers cannot drift from what the verifier actually proved.",
                "",
                f"- Functions represented by reviewed C: "
                f"**{manifest['recovered_functions']:,}**",
                f"- Original instruction bytes those functions occupy: "
                f"**{manifest['recovered_bytes']:,}**",
                "",
                "| Build | Exact functions | Exact bytes |",
                "|---|---:|---:|",
            ]
            + [
                f"| {version} | {manifest['exact'][version]['functions']:,} | "
                f"{manifest['exact'][version]['bytes']:,} |"
                for version in ("us", "lrg_rev1", "jp", "eu")
            ]
            + [
                "",
                "Behavior recovery means an independently written specification and C candidate "
                "exist. It does not count as matching decompilation until the identified original "
                "compiler reproduces the canonical bytes.",
                "",
            ]
        )

    lines.extend(
        [
            "",
            "## Compiler-family signal",
            "",
            f"The analysis interval contains **{compiler['beq_zero_zero_pseudo_branches']:,}** "
            f"IDO-style unconditional pseudo-branches and **{compiler['absolute_j_instructions']:,}** "
            f"absolute `j` instructions. Current hypothesis: **{compiler['hypothesis']}**.",
            "",
            (
                f"The accepted recovered-leaf profile is **{bootstrap['matching_profile']}**. "
                "Compiler choices may still vary elsewhere in the program."
                if bootstrap is not None and bootstrap.get("matching_profile")
                else "This does not yet identify the exact compiler release or flags."
            ),
        ]
    )

    lines.extend(["", "## Cross-version structural matches", "", "| Target | Unique matches | Coverage | Relocation deltas |", "|---|---:|---:|---:|"])
    for target_id, target in mappings["targets"].items():
        lines.append(
            f"| {target_id} | {target['unique_matches']:,}/{target['candidate_count']:,} | "
            f"{target['unique_match_percent']:.2f}% | {target['distinct_deltas']} |"
        )

    lines.extend(
        [
            "",
            "These mappings are strong same-source and boundary evidence, but they are not a "
            "decompilation percentage. Each candidate and segment boundary still needs verification.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--functions", type=Path, required=True)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--mappings", type=Path, required=True)
    parser.add_argument("--bootstrap", type=Path)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    rebuilds = [load(path) for path in sorted(args.output.parent.glob("rebuild.*.json"))]
    report = render_report(
        load(args.inventory),
        load(args.functions),
        load(args.compiler),
        load(args.mappings),
        rebuilds,
        load(args.bootstrap) if args.bootstrap is not None else None,
        load(args.manifest) if args.manifest is not None else None,
    )
    if not report.endswith("\n"):
        report += "\n"
    args.output.write_text(report, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
